version: '3'

networks:
  some-bridge:
    driver: bridge

services:
  app: 
    container_name: sl_web_api
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: SL.WebAPI/Dockerfile
    depends_on: 
      postgres_db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID=admin;Password=root;Host=postgres_db;Port=5432;Database=SLDatabase;
    networks:
      - some-bridge

  postgres_db:
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:latest
    networks:
      - some-bridge
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5